apiVersion: networking.k8s.io/v1  # API version for Ingress resource. 'networking.k8s.io/v1' is the stable version.
kind: Ingress  # Specifies that this is an Ingress resource.
metadata:
  name: dotnet-app-ingress  # Name of the Ingress resource.
  namespace: default  # Namespace where the Ingress is deployed.
  labels:  # Labels to categorize and select the Ingress.
    app: dotnet-app
    environment: production
  annotations:  # Annotations provide metadata for Ingress controllers and tools.
    nginx.ingress.kubernetes.io/rewrite-target: /  # Rewrites the URL path to root.
    nginx.ingress.kubernetes.io/ssl-redirect: "true"  # Forces HTTPS redirection.
    nginx.ingress.kubernetes.io/use-regex: "true"  # Enables regex in paths.
    kubernetes.io/ingress.class: "nginx"  # Specifies the Ingress controller to use (e.g., nginx, traefik).
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"  # Max body size for requests.

spec:
  ingressClassName: nginx  # Specifies the IngressClass resource to use.
  defaultBackend:  # Optional: fallback backend if no rules match.
    service:
      name: dotnet-app-service
      port:
        number: 80

  tls:  # TLS configuration for HTTPS.
    - hosts:
        - dotnet.example.com  # Domain name for TLS.
      secretName: dotnet-tls-secret  # Secret containing TLS certificate and key.

  rules:  # Routing rules for the Ingress.
    - host: dotnet.example.com  # Hostname to match.
      http:
        paths:
          - path: /  # Path to match.
            pathType: Prefix  # Path matching strategy: Prefix, Exact, or ImplementationSpecific.
            backend:
              service:
                name: dotnet-app-service  # Name of the service to route to.
                port:
                  number: 80  # Port on the service to route traffic to.
