apiVersion: v1  # API version for core Kubernetes resources like ServiceAccount
kind: ServiceAccount  # Declares this resource as a ServiceAccount

metadata:
  name: dotnet-service-account  # Unique name for the ServiceAccount
  namespace: default  # Namespace where the ServiceAccount is created
  labels:  # Optional labels to categorize and select the ServiceAccount
    app: dotnet-app
    environment: production
  annotations:  # Optional annotations for tooling, documentation, or automation
    description: "ServiceAccount for .NET application pods"

automountServiceAccountToken: true
# If true (default), mounts the service account token into the pod.
# Set to false to prevent automatic mounting for security-sensitive workloads.

secrets:
  - name: dotnet-app-secret
  # Optional list of secrets associated with this ServiceAccount.
  # These secrets must exist in the same namespace.
  # Typically used for legacy token-based access or custom credentials.

imagePullSecrets:
  - name: my-registry-secret
  # Optional list of secrets used to pull images from private registries.
  # These secrets must be of type:
  # - kubernetes.io/dockerconfigjson (recommended)
  # - kubernetes.io/dockercfg (legacy)
